# Generated by Django 4.0.6 on 2023-07-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('receiver', models.CharField(max_length=128)),
                ('sender', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PACKING', 'Пакуется'), ('ON_THE_MAY', 'В пути'), ('READY_TO_TAKE', 'Готов к выдаче')], default='PACKING', max_length=16, verbose_name='Статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
